### ISSUE TITLE
Not launching the UI after pickle error

### ISSUE THREAD

**Issue by mgks** [cocktailpeanut/bark.pinokio#3]
Nothing happens after this:
```
Traceback (most recent call last):
  File "C:\pinokio\api\bark.pinokio.git\app.py", line 30, in <module>
    tts = TTS("tts_models/multilingual/multi-dataset/bark", gpu=torch.cuda.is_available())
  File "C:\pinokio\api\bark.pinokio.git\env\lib\site-packages\TTS\api.py", line 81, in __init__
    self.load_tts_model_by_name(model_name, gpu)
  File "C:\pinokio\api\bark.pinokio.git\env\lib\site-packages\TTS\api.py", line 185, in load_tts_model_by_name
    self.synthesizer = Synthesizer(
  File "C:\pinokio\api\bark.pinokio.git\env\lib\site-packages\TTS\utils\synthesizer.py", line 109, in __init__
    self._load_tts_from_dir(model_dir, use_cuda)
  File "C:\pinokio\api\bark.pinokio.git\env\lib\site-packages\TTS\utils\synthesizer.py", line 164, in _load_tts_from_dir
    self.tts_model.load_checkpoint(config, checkpoint_dir=model_dir, eval=True)
  File "C:\pinokio\api\bark.pinokio.git\env\lib\site-packages\TTS\tts\models\bark.py", line 281, in load_checkpoint
    self.load_bark_models()
  File "C:\pinokio\api\bark.pinokio.git\env\lib\site-packages\TTS\tts\models\bark.py", line 50, in load_bark_models
    self.semantic_model, self.config = load_model(
  File "C:\pinokio\api\bark.pinokio.git\env\lib\site-packages\TTS\tts\layers\bark\load_model.py", line 121, in load_model
    checkpoint = torch.load(ckpt_path, map_location=device)
  File "C:\pinokio\api\bark.pinokio.git\env\lib\site-packages\torch\serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "C:\pinokio\api\bark.pinokio.git\env\lib\site-packages\torch\serialization.py", line 1033, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '<'.
```

**Comment by CLICKEARNER** [comment]
same here

**Comment by 91Abdullah** [comment]
@mgks Did you find any solution?

**Comment by mgks** [comment]
@91Abdullah just wipe it completely from your system and reinstall, might work sometimes.
recent updates are quite unstable.

not sure if this issue has been recognized by the developers.

**Comment by 91Abdullah** [comment]
Thanks @mgks for the help. I just removed the cache folder ("pinokio\cache\XDG_DATA_HOME\tts\tts_models--multilingual--multi-dataset--bark") and then it was forced to download the model again. Works fine now!

**Comment by mgks** [comment]
I guess we all have to find our own ways to make it work. closing this issue for now.
