### ISSUE TITLE
macOS cannot find cache/XDG_DATA_HOME/tts/tts_models

### ISSUE THREAD

**Issue by enzyme69** [cocktailpeanut/bark.pinokio#8]
```
 > tts_models/multilingual/multi-dataset/bark is already downloaded.
Traceback (most recent call last):
  File "/Users/jimmygunawan/pinokio/api/bark.pinokio.git/app.py", line 30, in <module>
    tts = TTS("tts_models/multilingual/multi-dataset/bark", gpu=torch.cuda.is_available())
  File "/Users/jimmygunawan/pinokio/api/bark.pinokio.git/env/lib/python3.10/site-packages/TTS/api.py", line 81, in __init__
    self.load_tts_model_by_name(model_name, gpu)
  File "/Users/jimmygunawan/pinokio/api/bark.pinokio.git/env/lib/python3.10/site-packages/TTS/api.py", line 185, in load_tts_model_by_name
    self.synthesizer = Synthesizer(
  File "/Users/jimmygunawan/pinokio/api/bark.pinokio.git/env/lib/python3.10/site-packages/TTS/utils/synthesizer.py", line 109, in __init__
    self._load_tts_from_dir(model_dir, use_cuda)
  File "/Users/jimmygunawan/pinokio/api/bark.pinokio.git/env/lib/python3.10/site-packages/TTS/utils/synthesizer.py", line 161, in _load_tts_from_dir
    config = load_config(os.path.join(model_dir, "config.json"))
  File "/Users/jimmygunawan/pinokio/api/bark.pinokio.git/env/lib/python3.10/site-packages/TTS/config/__init__.py", line 91, in load_config
    with fsspec.open(config_path, "r", encoding="utf-8") as f:
  File "/Users/jimmygunawan/pinokio/api/bark.pinokio.git/env/lib/python3.10/site-packages/fsspec/core.py", line 102, in __enter__
    f = self.fs.open(self.path, mode=mode)
  File "/Users/jimmygunawan/pinokio/api/bark.pinokio.git/env/lib/python3.10/site-packages/fsspec/spec.py", line 1241, in open
    f = self._open(
  File "/Users/jimmygunawan/pinokio/api/bark.pinokio.git/env/lib/python3.10/site-packages/fsspec/implementations/local.py", line 184, in _open
    return LocalFileOpener(path, mode, fs=self, **kwargs)
  File "/Users/jimmygunawan/pinokio/api/bark.pinokio.git/env/lib/python3.10/site-packages/fsspec/implementations/local.py", line 315, in __init__
    self._open()
  File "/Users/jimmygunawan/pinokio/api/bark.pinokio.git/env/lib/python3.10/site-packages/fsspec/implementations/local.py", line 320, in _open
    self.f = open(self.path, mode=self.mode)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/jimmygunawan/pinokio/cache/XDG_DATA_HOME/tts/tts_models--multilingual--multi-dataset--bark/config.json'
```

**Comment by tjtate** [comment]
same
